CREATE TABLE visits(id INT AUTO_INCREMENT PRIMARY KEY,ip VARCHAR(45),user_agent TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE downloads(id INT AUTO_INCREMENT PRIMARY KEY,ip VARCHAR(45),user_agent TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE admins(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50),password VARCHAR(255));
INSERT INTO admins(username,password) VALUES('admin','$2y$10$wJ6nSMj1k6A4uQjO2r4f9eP5hFX5P4M6k4T0hF9U6qqN9xvN4k1mG');
